name: go vet and comment
on:
  pull_request:
    branches:
      - main

jobs:
  govet:
    name: go vet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: git config --global url."https://ytakaya:${TOKEN}@github.com".insteadOf "https://github.com"
        
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        
      - name: install vettool
        run : go install github.com/ytalaya/vettool-example@latest
        
      - name: run vet
        run: go vet -vettool=myvet >> result
        
      - name: Comment
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'test'
            })
