name: go vet and comment
on:
  pull_request:
    branches:
      - main

jobs:
  govet:
    name: go vet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: git config --global url."https://ytakaya:${TOKEN}@github.com".insteadOf "https://github.com"
        
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        
      - name: install vettool
        run : GOBIN=$(pwd) GOPRIVATE="github.com/ytakaya/vettool-example" go install github.com/ytakaya/vettool-example@latest
        
      - name: run vet
        run: go vet -vettool=$(pwd)/vettool-example | tee result
            
      - name: Comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.comments_url }}
        run: |
          cat result
          curl -X POST \
              -H "Authorization: token ${GITHUB_TOKEN}" \
              -d "{\"body\": \"$(cat result)\"}" \
              ${URL}
